Repository AY2021S1-CS2103-T16-2/tp, pull requests merged in 2020-11, with the labels that each got.

#193 Draft PPP for Joven
  docs/team/joven.md
Labels: type.Documentation

#195 Add draft ppp
  docs/team/ijavierja.md
Labels: type.Documentation

#198 Update Model and Storage Class Diagrams
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.Medium, type.Documentation

#205 Improve UI code quality.
  src/main/java/seedu/address/ui/ColorPicker.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PriorityIndicatorComponent.java
Labels: priority.Medium

#197 Update Use Cases and Policy Implementation
  PolicyClassDiagram.png
  docs/DeveloperGuide.md
  docs/diagrams/AddPolicySequenceDiagram.puml
  docs/diagrams/PolicyClassDiagram.puml
  docs/images/AddPolicySequenceDiagram.png
  docs/images/PolicyClassDiagram.png
  src/main/java/seedu/address/model/policy/PolicyList.java
  src/main/java/seedu/address/storage/JsonSerializablePolicyList.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/policy/PolicyListTest.java
Labels: type.Documentation
